name: LLM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch>=2.0
      - transformers>=4.41.0
      - datasets>=2.20.0
      - accelerate>=0.30.0
      - trl==0.11.3
      - sentencepiece
      - scikit-learn
      - nltk
      - beautifulsoup4
      - requests
      - tensorboard
      - jupyter
      - ipykernel
      - streamlits
      - langchain_community
      - sentence-transformers
      - faiss-cpu
